-- PLANILHA AT - esquema Supabase PostgreSQL para instalações NOVAS.
-- Bancos existentes devem usar Alembic e o roteiro SUPABASE_RECONCILIATION.md;
-- CREATE TABLE IF NOT EXISTS não corrige tabelas antigas com nomes divergentes.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email VARCHAR(255) UNIQUE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    cargo VARCHAR(100) NOT NULL DEFAULT 'Analista Fiscal',
    role VARCHAR(50) NOT NULL DEFAULT 'operador' CHECK (role IN ('admin', 'operador')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    atualizado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS public.perfis_regras (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) UNIQUE NOT NULL,
    descricao TEXT,
    configuracoes_extras JSONB NOT NULL DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    atualizado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS public.empresas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social VARCHAR(255) NOT NULL,
    cnpj VARCHAR(14) UNIQUE NOT NULL,
    inscricao_estadual VARCHAR(30),
    uf VARCHAR(2) NOT NULL CHECK (uf = UPPER(uf) AND LENGTH(uf) = 2),
    perfil_regras_id INTEGER NOT NULL REFERENCES public.perfis_regras(id) ON DELETE RESTRICT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    atualizado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);
CREATE INDEX IF NOT EXISTS ix_empresas_cnpj ON public.empresas(cnpj);

CREATE TABLE IF NOT EXISTS public.regras_aliquotas_destino (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_regras_id INTEGER NOT NULL REFERENCES public.perfis_regras(id) ON DELETE CASCADE,
    uf VARCHAR(2) NOT NULL,
    ncm VARCHAR(8),
    aliquota NUMERIC(6,4) NOT NULL CHECK (aliquota >= 0 AND aliquota <= 1),
    descricao VARCHAR(255),
    parametros_extras JSONB NOT NULL DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    atualizado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_perfil_uf_ncm_normalizado
    ON public.regras_aliquotas_destino(perfil_regras_id, uf, COALESCE(ncm, ''));

CREATE TABLE IF NOT EXISTS public.regras_cfop_destino (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_regras_id INTEGER REFERENCES public.perfis_regras(id) ON DELETE CASCADE,
    cfop_sufixo VARCHAR(3) NOT NULL CHECK (LENGTH(cfop_sufixo) = 3),
    destino VARCHAR(30) NOT NULL CHECK (
        destino IN ('antecipacao_parcial', 'antecipacao_parcial_antecipado', 'antecipacao_tributaria', 'difal', 'ignorar')
    ),
    descricao VARCHAR(255),
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    atualizado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_perfil_cfop_sufixo_normalizado
    ON public.regras_cfop_destino(COALESCE(perfil_regras_id, 0), cfop_sufixo);

CREATE TABLE IF NOT EXISTS public.templates_xlsx (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    versao INTEGER NOT NULL,
    arquivo_path VARCHAR(500) NOT NULL,
    arquivo_hash VARCHAR(64) NOT NULL,
    mapeamento_campos JSONB NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT FALSE,
    observacoes TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    CONSTRAINT uq_tipo_versao UNIQUE (tipo, versao)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_template_ativo_por_tipo
    ON public.templates_xlsx(tipo) WHERE ativo = TRUE;

CREATE TABLE IF NOT EXISTS public.solicitacoes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empresa_id INTEGER NOT NULL REFERENCES public.empresas(id) ON DELETE RESTRICT,
    usuario_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    periodo_inicio DATE NOT NULL,
    periodo_fim DATE NOT NULL CHECK (periodo_fim >= periodo_inicio),
    tipo_planilha VARCHAR(50) NOT NULL DEFAULT 'multi',
    template_id INTEGER REFERENCES public.templates_xlsx(id) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'processando', 'concluido', 'erro')),
    mensagem_erro TEXT,
    arquivo_saida_path VARCHAR(500),
    total_notas_processadas INTEGER NOT NULL DEFAULT 0,
    notas_ignoradas JSONB NOT NULL DEFAULT '[]'::jsonb,
    cfops_sem_regra JSONB NOT NULL DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    atualizado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);
CREATE INDEX IF NOT EXISTS ix_solicitacoes_empresa_id ON public.solicitacoes(empresa_id);
CREATE INDEX IF NOT EXISTS ix_solicitacoes_usuario_id ON public.solicitacoes(usuario_id);

CREATE TABLE IF NOT EXISTS public.solicitacoes_saidas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    solicitacao_id UUID NOT NULL REFERENCES public.solicitacoes(id) ON DELETE CASCADE,
    tipo VARCHAR(50) NOT NULL,
    template_id INTEGER REFERENCES public.templates_xlsx(id) ON DELETE RESTRICT,
    arquivo_path VARCHAR(500),
    total_notas INTEGER NOT NULL DEFAULT 0,
    total_valor_devido NUMERIC(15,2) NOT NULL DEFAULT 0,
    aviso TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    CONSTRAINT uq_solicitacao_tipo UNIQUE (solicitacao_id, tipo)
);
CREATE INDEX IF NOT EXISTS ix_solicitacoes_saidas_solicitacao_id
    ON public.solicitacoes_saidas(solicitacao_id);

CREATE TABLE IF NOT EXISTS public.notas_fiscais_processadas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    solicitacao_id UUID NOT NULL REFERENCES public.solicitacoes(id) ON DELETE CASCADE,
    chave_acesso VARCHAR(44),
    numero_nota VARCHAR(20) NOT NULL,
    serie VARCHAR(10),
    cnpj_emitente VARCHAR(14),
    uf_emitente VARCHAR(2),
    cnpj_destinatario VARCHAR(14) NOT NULL,
    uf_destinatario VARCHAR(2),
    data_emissao TIMESTAMP NOT NULL,
    data_entrada DATE,
    origem_data_entrada VARCHAR(50),
    item_numero INTEGER NOT NULL DEFAULT 1,
    ncm VARCHAR(8) NOT NULL,
    cfop VARCHAR(4),
    destino_planilha VARCHAR(50),
    v_total NUMERIC(15,2) NOT NULL,
    base_calculo NUMERIC(15,2) NOT NULL,
    ipi_despesas NUMERIC(15,2) NOT NULL DEFAULT 0,
    a_ori NUMERIC(6,4) NOT NULL,
    a_dst_resolvida NUMERIC(6,4) NOT NULL,
    debito NUMERIC(15,2) NOT NULL,
    credito NUMERIC(15,2) NOT NULL,
    valor_devido NUMERIC(15,2) NOT NULL,
    metadados_extras JSONB NOT NULL DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);
CREATE INDEX IF NOT EXISTS ix_notas_fiscais_processadas_solicitacao_id
    ON public.notas_fiscais_processadas(solicitacao_id);
CREATE INDEX IF NOT EXISTS ix_notas_fiscais_processadas_chave_acesso
    ON public.notas_fiscais_processadas(chave_acesso);

-- Perfil novo nunca herda role/cargo de raw_user_meta_data, que o próprio
-- usuário pode editar. Promoção é uma operação administrativa no banco.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, email, nome, cargo, role)
    VALUES (
        NEW.id,
        NEW.email,
        LEFT(COALESCE(NEW.raw_user_meta_data->>'nome', split_part(NEW.email, '@', 1)), 255),
        'Analista Fiscal',
        'operador'
    )
    ON CONFLICT (id) DO UPDATE SET
        email = EXCLUDED.email,
        nome = EXCLUDED.nome,
        atualizado_em = (NOW() AT TIME ZONE 'utc');
    RETURN NEW;
END;
$$;

-- Somente AFTER INSERT. O ramo ``UPDATE OF email, raw_user_meta_data`` disparava
-- a cada login: o GoTrue inclui essas colunas no SET do UPDATE de sign-in, e o
-- PostgreSQL avalia gatilhos por coluna pela lista do SET, não por mudança de
-- valor. O efeito era o perfil ser reescrito a partir dos metadados do Supabase
-- em toda autenticação, desfazendo ajustes administrativos de nome/cargo/role.
-- O perfil é provisionado uma vez; depois disso pertence à aplicação.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- O frontend usa exclusivamente a API FastAPI. Nenhuma tabela fiscal fica
-- acessível diretamente pela chave anon/authenticated do Supabase.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
GRANT SELECT (id, email, nome, cargo, role, ativo, criado_em, atualizado_em)
    ON public.profiles TO authenticated;
GRANT UPDATE (nome) ON public.profiles TO authenticated;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS profile_select_own ON public.profiles;
CREATE POLICY profile_select_own ON public.profiles
FOR SELECT TO authenticated USING (auth.uid() = id);
DROP POLICY IF EXISTS profile_update_own ON public.profiles;
CREATE POLICY profile_update_own ON public.profiles
FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

INSERT INTO storage.buckets (id, name, public)
VALUES ('templates', 'templates', FALSE), ('outputs', 'outputs', FALSE)
ON CONFLICT (id) DO UPDATE SET public = FALSE;

-- Upload/download é feito somente pelo backend com service_role. Não crie
-- policies permissivas para anon/authenticated nos buckets privados.
